name: Integration Tests

on: 
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build containers
      run: make containers
    - name: docker-compose up
      run: docker-compose up -d
      working-directory: ./integration_tests
    - name: Test
      run: ./test.sh
      working-directory: ./integration_tests
