name: Test Node

on: 
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: Test Node
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build test image
      run: make test-image
    - name: Build Node
      run: |
        make -C ./node
    - name: Lint
      run: |
        make lint -C ./node
    - name: Test
      run: |
        make test -C ./node
