name: Test Pilot

on: 
    pull_request:
    push:
      branches: 
        - master
jobs:

  test:
    name: Test Pilot
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make build -C ./pilot
    - name: Pilot
      run: make pilot -C ./pilot
    - name: Test
      run: make test -C ./pilot