name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build test image
      run: docker build . --file dockerfile --tag test
    - name: make
      run: |
        make -C ./node
    - name: make lint
      run: |
        make lint -C ./node
    - name: make test
      run: |
        make test -C ./node
